### ISSUE TITLE
rollDamage - Weapon name not shown

### ISSUE THREAD

**Issue by Xacus** [Perfectro/symbaroum-foundry-vtt#2]
Line 198 in main-sheet.js

Replace "weapon.data.data.name" with "weapon.name"

**Comment by Perfectro** [comment]
There is no `main-sheet.js` file. Are you up to date ?
I doesn't see any problem with the name of the weapon on my side.
![image](https://user-images.githubusercontent.com/5683489/90422818-b2b60180-e0bb-11ea-9030-a5a5d8c634d5.png)

**Comment by Xacus** [comment]
Strange. I had to uninstall and remove the system. Apparently it didn't update automatically.
