### ISSUE TITLE
"Backward" compat

### ISSUE THREAD

**Issue by Raldanash** [Perfectro/symbaroum-foundry-vtt#4]
I updated the system / character sheets and this made the dozens of actors I had previously configured inaccessible, including the party. Is this expected? Is there a way to migrate these actors? Same applies to some generic items, but that is less of a problem.
*** When trying to add the actors to a compendium, an error pops up : You must define a valid actor type"
Thanks!

**Comment by Perfectro** [comment]
It is expected : https://github.com/Perfectro/symbaroum-foundry-vtt/releases/tag/v2.0
